services:
  db:
    image: mysql:9.0.1
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=inventory_invoice_db
      - MYSQL_ROOT_PASSWORD=ZZ@"4._V(q9z^j&j
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local